const $=id=>document.getElementById(id);
const state={parts:[],selected:null,house:{img:null,walls:[],calPts:[],pxPerRealMm:0,mode:'',draft:null},photo:{img:null}};
const status=(id,msg,warn=false)=>{const e=$(id);e.textContent=msg;e.classList.toggle('warn',warn)};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');state.house.draft=null;drawHouse()});
function tri(a,b,c){return 'facet normal 0 0 0\n outer loop\n  vertex '+a.join(' ')+'\n  vertex '+b.join(' ')+'\n  vertex '+c.join(' ')+'\n endloop\nendfacet\n'}
function boxFacets(x,y,z,w,d,h){const p=[[x,y,z],[x+w,y,z],[x+w,y+d,z],[x,y+d,z],[x,y,z+h],[x+w,y,z+h],[x+w,y+d,z+h],[x,y+d,z+h]],q=[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,0,4],[3,4,7]];return q.map(t=>tri(p[t[0]],p[t[1]],p[t[2]])).join('')}
function cylFacets(cx,cy,z,r,h,n=64){let s='';for(let i=0;i<n;i++){let a=i*2*Math.PI/n,b=(i+1)*2*Math.PI/n,p=[cx+r*Math.cos(a),cy+r*Math.sin(a),z],q=[cx+r*Math.cos(b),cy+r*Math.sin(b),z],P=[p[0],p[1],z+h],Q=[q[0],q[1],z+h];s+=tri([cx,cy,z],q,p)+tri([cx,cy,z+h],P,Q)+tri(p,q,Q)+tri(p,Q,P)}return s}
function saveSTL(name,facets){const blob=new Blob(['solid '+name+'\n'+facets+'endsolid '+name+'\n'],{type:'model/stl'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.stl';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function readPart(){const shape=$('partShape').value,w=+$('partW').value,d=+$('partD').value,h=+$('partH').value,x=+$('partX').value,y=+$('partY').value,z=+$('partZ').value;return{id:crypto.randomUUID(),shape,w:Math.max(.1,w),d:Math.max(.1,d),h:Math.max(.1,h),x,y,z}}
$('addPart').onclick=()=>{state.parts.push(readPart());state.selected=state.parts.at(-1).id;renderParts()};
$('updatePart').onclick=()=>{const i=state.parts.findIndex(p=>p.id===state.selected);if(i<0)return status('customInfo','Select a piece first.',true);state.parts[i]={...readPart(),id:state.selected};renderParts()};
$('deletePart').onclick=()=>{state.parts=state.parts.filter(p=>p.id!==state.selected);state.selected=null;renderParts()};
$('clearParts').onclick=()=>{if(confirm('Clear all custom pieces?')){state.parts=[];state.selected=null;renderParts()}};
function selectPart(id){state.selected=id;const p=state.parts.find(x=>x.id===id);if(p){$('partShape').value=p.shape;$('partW').value=p.w;$('partD').value=p.d;$('partH').value=p.h;$('partX').value=p.x;$('partY').value=p.y;$('partZ').value=p.z}renderParts()}
function renderParts(){const list=$('partList');list.innerHTML='';state.parts.forEach((p,i)=>{const b=document.createElement('button');b.className=p.id===state.selected?'selected':'';b.textContent=(i+1)+'. '+p.shape+' — '+p.w+'×'+p.d+'×'+p.h+' mm @ '+p.x+','+p.y+','+p.z;b.onclick=()=>selectPart(p.id);list.append(b)});drawCustom();status('customInfo',state.parts.length?state.parts.length+' printable solid'+(state.parts.length===1?'':'s')+' ready.':'Add a piece to start.')}
function drawCustom(){const c=$('customCanvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);c.onclick=null;if(!state.parts.length)return;let minX=Math.min(...state.parts.map(p=>p.shape==='cylinder'?p.x-p.w/2:p.x)),minY=Math.min(...state.parts.map(p=>p.shape==='cylinder'?p.y-p.w/2:p.y)),maxX=Math.max(...state.parts.map(p=>p.shape==='cylinder'?p.x+p.w/2:p.x+p.w)),maxY=Math.max(...state.parts.map(p=>p.shape==='cylinder'?p.y+p.w/2:p.y+p.d));const sc=Math.min(700/Math.max(1,maxX-minX),500/Math.max(1,maxY-minY)),ox=(c.width-(maxX-minX)*sc)/2-minX*sc,oy=(c.height-(maxY-minY)*sc)/2-minY*sc;x.lineWidth=2;state.parts.forEach(p=>{x.fillStyle=p.id===state.selected?'rgba(14,165,233,.35)':'rgba(15,118,110,.25)';x.strokeStyle=p.id===state.selected?'#0284c7':'#0f766e';if(p.shape==='cylinder'){x.beginPath();x.arc(ox+p.x*sc,oy+p.y*sc,p.w/2*sc,0,7);x.fill();x.stroke()}else{x.fillRect(ox+p.x*sc,oy+p.y*sc,p.w*sc,p.d*sc);x.strokeRect(ox+p.x*sc,oy+p.y*sc,p.w*sc,p.d*sc)}});c.onclick=e=>{const r=c.getBoundingClientRect(),mx=(e.clientX-r.left)*c.width/r.width,my=(e.clientY-r.top)*c.height/r.height;for(const p of [...state.parts].reverse()){let hit=p.shape==='cylinder'?Math.hypot(mx-(ox+p.x*sc),my-(oy+p.y*sc))<=p.w/2*sc:mx>=ox+p.x*sc&&mx<=ox+(p.x+p.w)*sc&&my>=oy+p.y*sc&&my<=oy+(p.y+p.d)*sc;if(hit){selectPart(p.id);break}}}}
$('exportCustom').onclick=()=>{if(!state.parts.length)return status('customInfo','Add at least one piece first.',true);let s='';for(const p of state.parts)s+=p.shape==='cylinder'?cylFacets(p.x,p.y,p.z,p.w/2,p.h):boxFacets(p.x,p.y,p.z,p.w,p.d,p.h);saveSTL('custom-piece',s);status('customInfo','Custom STL exported.')};
function canvasPoint(c,e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
async function loadHouse(file){try{let im;if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){status('houseInfo','Rendering PDF page 1…');const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise,page=await pdf.getPage(1),vp=page.getViewport({scale:1.5}),tmp=document.createElement('canvas');tmp.width=vp.width;tmp.height=vp.height;await page.render({canvasContext:tmp.getContext('2d'),viewport:vp}).promise;im=new Image;await new Promise((res,rej)=>{im.onload=res;im.onerror=rej;im.src=tmp.toDataURL('image/png')})}else{im=new Image;const url=URL.createObjectURL(file);await new Promise((res,rej)=>{im.onload=res;im.onerror=rej;im.src=url});URL.revokeObjectURL(url)}state.house.img=im;state.house.walls=[];state.house.calPts=[];state.house.pxPerRealMm=0;state.house.draft=null;drawHouse();status('houseInfo','Plan loaded. Calibrate scale next.')}catch(err){status('houseInfo','Plan load failed: '+err.message,true)}}
$('houseFile').onchange=e=>e.target.files[0]&&loadHouse(e.target.files[0]);
$('calibrate').onclick=()=>{if(!state.house.img)return status('houseInfo','Load a plan first.',true);state.house.mode='cal';state.house.calPts=[];state.house.draft=null;status('houseInfo','Calibration active: click two points matching the known distance.')};
$('traceWalls').onclick=()=>{if(!state.house.pxPerRealMm)return status('houseInfo','Calibrate the plan first.',true);state.house.mode='trace';state.house.draft=null;status('houseInfo','Wall trace active. Click start and end of each wall.')};
$('undoWall').onclick=()=>{state.house.walls.pop();state.house.draft=null;drawHouse()};$('clearWalls').onclick=()=>{if(confirm('Clear traced walls?')){state.house.walls=[];state.house.draft=null;drawHouse()}};
function houseTransform(){const c=$('houseCanvas'),im=state.house.img;if(!im)return{sc:1,ox:0,oy:0};const sc=Math.min(c.width/im.width,c.height/im.height),ox=(c.width-im.width*sc)/2,oy=(c.height-im.height*sc)/2;return{sc,ox,oy}}
function drawHouse(){const c=$('houseCanvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);if(!state.house.img)return;const {sc,ox,oy}=houseTransform();x.drawImage(state.house.img,ox,oy,state.house.img.width*sc,state.house.img.height*sc);x.lineWidth=3;x.strokeStyle='#ef4444';state.house.walls.forEach(w=>{x.beginPath();x.moveTo(w.a.x,w.a.y);x.lineTo(w.b.x,w.b.y);x.stroke()});x.fillStyle='#22c55e';state.house.calPts.forEach(p=>{x.beginPath();x.arc(p.x,p.y,6,0,7);x.fill()});if(state.house.draft){x.fillStyle='#0284c7';x.beginPath();x.arc(state.house.draft.x,state.house.draft.y,6,0,7);x.fill()}}
$('houseCanvas').onclick=e=>{if(!state.house.img)return;const c=$('houseCanvas'),p=canvasPoint(c,e),{sc,ox,oy}=houseTransform();if(p.x<ox||p.y<oy||p.x>ox+state.house.img.width*sc||p.y>oy+state.house.img.height*sc)return;if(state.house.mode==='cal'){state.house.calPts.push(p);if(state.house.calPts.length===2){const dist=Math.hypot(state.house.calPts[1].x-state.house.calPts[0].x,state.house.calPts[1].y-state.house.calPts[0].y),known=Math.max(1,+$('knownMm').value);state.house.pxPerRealMm=dist/known;state.house.mode='';status('houseInfo','Calibrated: '+known+' mm = '+dist.toFixed(1)+' px. Select Trace Walls.')}drawHouse();return}if(state.house.mode==='trace'){if(!state.house.draft){state.house.draft=p}else{state.house.walls.push({a:state.house.draft,b:p});state.house.draft=null;status('houseInfo',state.house.walls.length+' wall'+(state.house.walls.length===1?'':'s')+' traced.')}drawHouse()}};
$('houseCanvas').ondblclick=e=>{e.preventDefault();state.house.draft=null;drawHouse()};document.addEventListener('keydown',e=>{if(e.key==='Escape'){state.house.draft=null;state.house.mode='';drawHouse()}});
function orientedWall(a,b,t,h,pxPerMm,scale){const ax=a.x/pxPerMm/scale,ay=a.y/pxPerMm/scale,bx=b.x/pxPerMm/scale,by=b.y/pxPerMm/scale,dx=bx-ax,dy=by-ay,L=Math.hypot(dx,dy),nx=-dy/L*t/2,ny=dx/L*t/2,p=[[ax+nx,ay+ny,0],[ax-nx,ay-ny,0],[bx-nx,by-ny,0],[bx+nx,by+ny,0],[ax+nx,ay+ny,h],[ax-nx,ay-ny,h],[bx-nx,by-ny,h],[bx+nx,by+ny,h]],q=[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,0,4],[3,4,7]];return q.map(z=>tri(p[z[0]],p[z[1]],p[z[2]])).join('')}
$('exportHouse').onclick=()=>{if(!state.house.pxPerRealMm||!state.house.walls.length)return status('houseInfo','Need a calibrated plan and traced walls first.',true);const scale=Math.max(1,+$('printScale').value),t=Math.max(1,+$('wallT').value)/scale,h=Math.max(1,+$('wallH').value)/scale;let s='';state.house.walls.forEach(w=>s+=orientedWall(w.a,w.b,t,h,state.house.pxPerRealMm,scale));saveSTL('house-walls-1-'+scale,s);status('houseInfo','House wall STL exported at 1:'+scale+'.')};
$('photoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const im=new Image,url=URL.createObjectURL(f);im.onload=()=>{state.photo.img=im;drawPhoto();status('photoInfo',im.width+'×'+im.height+' photo loaded.');URL.revokeObjectURL(url)};im.onerror=()=>status('photoInfo','Photo load failed.',true);im.src=url};
function drawPhoto(){const c=$('photoCanvas'),x=c.getContext('2d'),im=state.photo.img;x.clearRect(0,0,c.width,c.height);x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);if(!im)return;const sc=Math.min(c.width/im.width,c.height/im.height),w=im.width*sc,h=im.height*sc;x.drawImage(im,(c.width-w)/2,(c.height-h)/2,w,h)}$('refreshPhoto').onclick=drawPhoto;
$('exportPhoto').onclick=()=>{const im=state.photo.img;if(!im)return status('photoInfo','Load a photo first.',true);const nx=+$('photoRes').value,ny=Math.max(10,Math.round(nx*im.height/im.width)),tmp=document.createElement('canvas');tmp.width=nx;tmp.height=ny;const tx=tmp.getContext('2d',{willReadFrequently:true});tx.drawImage(im,0,0,nx,ny);const data=tx.getImageData(0,0,nx,ny).data,W=Math.max(10,+$('photoW').value),H=W*ny/nx,base=Math.max(.4,+$('photoBase').value),depth=Math.max(.2,+$('photoDepth').value),inv=$('photoInvert').checked,z=[];for(let y=0;y<ny;y++){z[y]=[];for(let x=0;x<nx;x++){let i=(y*nx+x)*4,lum=(data[i]+data[i+1]+data[i+2])/765;if(inv)lum=1-lum;z[y][x]=base+(1-lum)*depth}}let s='';for(let y=0;y<ny-1;y++)for(let x=0;x<nx-1;x++){const x0=x*W/(nx-1),x1=(x+1)*W/(nx-1),y0=y*H/(ny-1),y1=(y+1)*H/(ny-1),a=[x0,y0,z[y][x]],b=[x1,y0,z[y][x+1]],c=[x1,y1,z[y+1][x+1]],d=[x0,y1,z[y+1][x]];s+=tri(a,b,c)+tri(a,c,d)+tri([x0,y0,0],[x1,y1,0],[x1,y0,0])+tri([x0,y0,0],[x0,y1,0],[x1,y1,0])}for(let x=0;x<nx-1;x++){let x0=x*W/(nx-1),x1=(x+1)*W/(nx-1);s+=tri([x0,0,0],[x1,0,z[0][x+1]],[x1,0,0])+tri([x0,0,0],[x0,0,z[0][x]],[x1,0,z[0][x+1]]);s+=tri([x0,H,0],[x1,H,0],[x1,H,z[ny-1][x+1]])+tri([x0,H,0],[x1,H,z[ny-1][x+1]],[x0,H,z[ny-1][x]])}for(let y=0;y<ny-1;y++){let y0=y*H/(ny-1),y1=(y+1)*H/(ny-1);s+=tri([0,y0,0],[0,y1,0],[0,y1,z[y+1][0]])+tri([0,y0,0],[0,y1,z[y+1][0]],[0,y0,z[y][0]]);s+=tri([W,y0,0],[W,y1,z[y+1][nx-1]],[W,y1,0])+tri([W,y0,0],[W,y0,z[y][nx-1]],[W,y1,z[y+1][nx-1]])}saveSTL('photo-relief',s);status('photoInfo','Relief STL exported: '+W.toFixed(1)+' × '+H.toFixed(1)+' mm.')};
function serialise(){return{version:1,parts:state.parts,house:{walls:state.house.walls,pxPerRealMm:state.house.pxPerRealMm},settings:{knownMm:$('knownMm').value,printScale:$('printScale').value,wallT:$('wallT').value,wallH:$('wallH').value,photoW:$('photoW').value,photoBase:$('photoBase').value,photoDepth:$('photoDepth').value,photoRes:$('photoRes').value}}}
function applyProject(p){state.parts=p.parts||[];state.house.walls=p.house?.walls||[];state.house.pxPerRealMm=p.house?.pxPerRealMm||0;Object.entries(p.settings||{}).forEach(([k,v])=>$(k)&&($(k).value=v));renderParts();drawHouse()}
$('saveProject').onclick=()=>{localStorage.setItem('plans-to-print.project',JSON.stringify(serialise()));alert('Plans to Print work saved on this device.')};
$('exportProject').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(serialise(),null,2)],{type:'application/json'}));a.download='plans-to-print-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('importProject').onchange=async e=>{try{applyProject(JSON.parse(await e.target.files[0].text()))}catch(err){alert('Could not open project: '+err.message)}};
try{const saved=localStorage.getItem('plans-to-print.project');if(saved)applyProject(JSON.parse(saved))}catch{}renderParts();drawHouse();drawPhoto();