import { mountHouseModelWorkspace } from './house-model-workspace.js';

const style = document.createElement('style');
style.textContent = `:root{font-family:system-ui,sans-serif;color:#e7edf3;background:#101827}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1100px;margin:auto;padding:22px}header{border-bottom:1px solid #314158}h1{margin:0}header p{color:#aab7c7}.tabs,.house-actions{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}button{border:0;border-radius:8px;padding:10px 13px;background:#26354a;color:inherit;cursor:pointer}button.active,button.primary{background:#0d9b7b}button:disabled{opacity:.5}.card,.house-model{background:#172235;border:1px solid #314158;border-radius:12px;padding:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}label{display:grid;gap:5px;margin:8px 0}input,select{padding:9px;border-radius:7px;border:1px solid #526176;background:#0e1624;color:inherit}.preview{padding:16px;margin-top:12px;border:1px dashed #526176;border-radius:8px}.house-model canvas{display:block;max-width:100%;height:auto;border:1px solid #526176;background:#fff;margin:12px 0;touch-action:manipulation}.house-model fieldset{border:1px solid #314158;border-radius:8px;margin:12px 0}.error{color:#ff9b9b}@media(max-width:600px){.wrap{padding:12px}}`;
document.head.append(style);

function download(name, text) { const url = URL.createObjectURL(new Blob([text], { type: 'model/stl' })); const link = Object.assign(document.createElement('a'), { href: url, download: name }); link.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }
function facet(lines, a, b, c) { lines.push('facet normal 0 0 0', ' outer loop', `  vertex ${a.join(' ')}`, `  vertex ${b.join(' ')}`, `  vertex ${c.join(' ')}`, ' endloop', 'endfacet'); }
function boxStl(width, depth, height) { const p=[[0,0,0],[width,0,0],[width,depth,0],[0,depth,0],[0,0,height],[width,0,height],[width,depth,height],[0,depth,height]]; const faces=[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,0,4],[3,4,7]]; const lines=['solid plan2print-part']; faces.forEach(([a,b,c])=>facet(lines,p[a],p[b],p[c])); return `${lines.join('\n')}\nendsolid plan2print-part`; }
function setupPartPanel(panel, type) { panel.innerHTML=`<div class="card"><h2>${type === 'hook' ? 'Storage & Hooks' : type === 'image' ? 'Image / Lithophane' : 'Custom printable part'}</h2><p>${type === 'image' ? 'Choose a photo to size a simple printable plaque.' : 'Set the size in millimetres and export a real STL.'}</p>${type === 'image' ? '<label>Photo <input data-photo type="file" accept="image/*"></label>' : ''}<div class="grid"><label>Width (mm)<input data-w type="number" value="${type === 'hook' ? 50 : 60}" min="1"></label><label>Depth (mm)<input data-d type="number" value="${type === 'hook' ? 35 : 40}" min="1"></label><label>Height (mm)<input data-h type="number" value="${type === 'hook' ? 8 : 12}" min="1"></label></div><button class="primary" data-export>Download STL</button><div class="preview" data-preview>Ready to export.</div></div>`; const inputs=['w','d','h'].map(k=>panel.querySelector(`[data-${k}]`)); const preview=panel.querySelector('[data-preview]'); const refresh=()=>preview.textContent=`${inputs[0].value} × ${inputs[1].value} × ${inputs[2].value} mm ${type === 'hook' ? 'hook blank' : 'part'}`; inputs.forEach(i=>i.addEventListener('input',refresh)); const photo=panel.querySelector('[data-photo]'); if (photo) photo.addEventListener('change',()=>{const file=photo.files?.[0]; if(!file)return; const image=new Image(); const url=URL.createObjectURL(file); image.onload=()=>{inputs[1].value=(Number(inputs[0].value)*image.height/image.width).toFixed(1); URL.revokeObjectURL(url); refresh(); preview.textContent=`Photo proportion applied: ${preview.textContent}`;}; image.src=url;}); refresh(); panel.querySelector('[data-export]').addEventListener('click',()=>download(`plan2print-${type}.stl`,boxStl(...inputs.map(i=>Math.max(1,Number(i.value)))))); }

const panels = Object.fromEntries([...document.querySelectorAll('[data-panel]')].map((panel) => [panel.dataset.panel, panel]));
setupPartPanel(panels.design, 'design'); setupPartPanel(panels.hooks, 'hook'); setupPartPanel(panels.image, 'image'); mountHouseModelWorkspace({ host: panels.house });
function choose(tab) { Object.entries(panels).forEach(([name,panel])=>{panel.hidden=name!==tab;}); document.querySelectorAll('[data-tab]').forEach(button=>button.classList.toggle('active',button.dataset.tab===tab)); }
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>choose(button.dataset.tab))); choose('design');
